console.log("Lista de Alunos");
let alunos = [
    'Viviane',
    'Victor',
    'Vanderson',
    'Samuel',
    'Rodrigo',
    'Rodrigo',
    'Raquel',
    'Rafael',
    'Pedro',
    'Pedro',
    'Núria',
    'Nathan',
    'Matheus',
    'Marcos',
    'Marcos',
    'Marcella',
    'Luciana',
    'Luciana',
    'Luana',
    'Leandro',
    'Karina',
    'Higor',
    'Gustavo',
    'Guilherme',
    'Gilnei',
    'Eduardo',
    'Diego',
    'Daniel',
    'Carolina',
    'Carlos',
    'Bruno',
    'Beatriz',
    'Angelita',
    'Andre',
    'Andre',
    'Adrian'
  ]
  
  console.log(alunos);  // opção console.log(alunos.sort().reverse());
