var quantidadeDeVendedores = 3
var endereçoCompleto = "Baker Street,  221B; Última Casa" 
var preçoEtanol = 3.84
var estadoLâmpada = false
var endereçoHifen = 3333-333
var displayElevador = 13
var ledElevador = true
var aniversarioProf = (23/02/1986)
var balançaRestaurante = 1.23kg 
var numeroDeBoisCurral = 320
var pascoa = 00/00/2021
var numeroDeLaranjasCaixa = 23
var vogal = a
var tituloLivro = "O Senhor dos Anéis"
var limiteCartão = 19900
var horarioTransmissaoJogo = (19:34)
var alturaPredio = 1594m 
var paginasCaderno = 120
var statusSalaReuniaoOcupada = True
var AlternativasMultiplaEscolha = "a)"